/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutopayRouteImport } from './routes/autopay'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GatewayRouteImport } from './routes/gateway'
import { Route as CompanyCodeRouteImport } from './routes/company.$code'
import { Route as PayCharityRouteImport } from './routes/pay.charity'
import { Route as PayMethodRouteImport } from './routes/pay.method'
import { Route as PayProcessingRouteImport } from './routes/pay.processing'
import { Route as PayVerifyRouteImport } from './routes/pay.verify'
import { Route as PaymentsIndexRouteImport } from './routes/payments.index'
import { Route as PaymentsIdRouteImport } from './routes/payments.$id'
import { Route as CompanyCodeLoginRouteImport } from './routes/company.$code.login'
import { Route as CompanyCodeSettingsRouteImport } from './routes/company.$code.settings'
import { Route as PayReceiptIdRouteImport } from './routes/pay.receipt.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutopayRoute = AutopayRouteImport.update({
  id: '/autopay',
  path: '/autopay',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GatewayRoute = GatewayRouteImport.update({
  id: '/gateway',
  path: '/gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCodeRoute = CompanyCodeRouteImport.update({
  id: '/company/$code',
  path: '/company/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PayCharityRoute = PayCharityRouteImport.update({
  id: '/pay/charity',
  path: '/pay/charity',
  getParentRoute: () => rootRouteImport,
} as any)
const PayMethodRoute = PayMethodRouteImport.update({
  id: '/pay/method',
  path: '/pay/method',
  getParentRoute: () => rootRouteImport,
} as any)
const PayProcessingRoute = PayProcessingRouteImport.update({
  id: '/pay/processing',
  path: '/pay/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const PayVerifyRoute = PayVerifyRouteImport.update({
  id: '/pay/verify',
  path: '/pay/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIdRoute = PaymentsIdRouteImport.update({
  id: '/payments/$id',
  path: '/payments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCodeLoginRoute = CompanyCodeLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CompanyCodeRoute,
} as any)
const CompanyCodeSettingsRoute = CompanyCodeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CompanyCodeRoute,
} as any)
const PayReceiptIdRoute = PayReceiptIdRouteImport.update({
  id: '/pay/receipt/$id',
  path: '/pay/receipt/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/autopay': typeof AutopayRoute
  '/contact': typeof ContactRoute
  '/gateway': typeof GatewayRoute
  '/company/$code': typeof CompanyCodeRouteWithChildren
  '/pay/charity': typeof PayCharityRoute
  '/pay/method': typeof PayMethodRoute
  '/pay/processing': typeof PayProcessingRoute
  '/pay/verify': typeof PayVerifyRoute
  '/payments/$id': typeof PaymentsIdRoute
  '/payments/': typeof PaymentsIndexRoute
  '/company/$code/login': typeof CompanyCodeLoginRoute
  '/company/$code/settings': typeof CompanyCodeSettingsRoute
  '/pay/receipt/$id': typeof PayReceiptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/autopay': typeof AutopayRoute
  '/contact': typeof ContactRoute
  '/gateway': typeof GatewayRoute
  '/company/$code': typeof CompanyCodeRouteWithChildren
  '/pay/charity': typeof PayCharityRoute
  '/pay/method': typeof PayMethodRoute
  '/pay/processing': typeof PayProcessingRoute
  '/pay/verify': typeof PayVerifyRoute
  '/payments/$id': typeof PaymentsIdRoute
  '/payments': typeof PaymentsIndexRoute
  '/company/$code/login': typeof CompanyCodeLoginRoute
  '/company/$code/settings': typeof CompanyCodeSettingsRoute
  '/pay/receipt/$id': typeof PayReceiptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/autopay': typeof AutopayRoute
  '/contact': typeof ContactRoute
  '/gateway': typeof GatewayRoute
  '/company/$code': typeof CompanyCodeRouteWithChildren
  '/pay/charity': typeof PayCharityRoute
  '/pay/method': typeof PayMethodRoute
  '/pay/processing': typeof PayProcessingRoute
  '/pay/verify': typeof PayVerifyRoute
  '/payments/$id': typeof PaymentsIdRoute
  '/payments/': typeof PaymentsIndexRoute
  '/company/$code/login': typeof CompanyCodeLoginRoute
  '/company/$code/settings': typeof CompanyCodeSettingsRoute
  '/pay/receipt/$id': typeof PayReceiptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/autopay'
    | '/contact'
    | '/gateway'
    | '/company/$code'
    | '/pay/charity'
    | '/pay/method'
    | '/pay/processing'
    | '/pay/verify'
    | '/payments/$id'
    | '/payments/'
    | '/company/$code/login'
    | '/company/$code/settings'
    | '/pay/receipt/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/autopay'
    | '/contact'
    | '/gateway'
    | '/company/$code'
    | '/pay/charity'
    | '/pay/method'
    | '/pay/processing'
    | '/pay/verify'
    | '/payments/$id'
    | '/payments'
    | '/company/$code/login'
    | '/company/$code/settings'
    | '/pay/receipt/$id'
  id:
    | '__root__'
    | '/'
    | '/autopay'
    | '/contact'
    | '/gateway'
    | '/company/$code'
    | '/pay/charity'
    | '/pay/method'
    | '/pay/processing'
    | '/pay/verify'
    | '/payments/$id'
    | '/payments/'
    | '/company/$code/login'
    | '/company/$code/settings'
    | '/pay/receipt/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutopayRoute: typeof AutopayRoute
  ContactRoute: typeof ContactRoute
  GatewayRoute: typeof GatewayRoute
  CompanyCodeRoute: typeof CompanyCodeRouteWithChildren
  PayCharityRoute: typeof PayCharityRoute
  PayMethodRoute: typeof PayMethodRoute
  PayProcessingRoute: typeof PayProcessingRoute
  PayVerifyRoute: typeof PayVerifyRoute
  PaymentsIdRoute: typeof PaymentsIdRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
  PayReceiptIdRoute: typeof PayReceiptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autopay': {
      id: '/autopay'
      path: '/autopay'
      fullPath: '/autopay'
      preLoaderRoute: typeof AutopayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gateway': {
      id: '/gateway'
      path: '/gateway'
      fullPath: '/gateway'
      preLoaderRoute: typeof GatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$code': {
      id: '/company/$code'
      path: '/company/$code'
      fullPath: '/company/$code'
      preLoaderRoute: typeof CompanyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/charity': {
      id: '/pay/charity'
      path: '/pay/charity'
      fullPath: '/pay/charity'
      preLoaderRoute: typeof PayCharityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/method': {
      id: '/pay/method'
      path: '/pay/method'
      fullPath: '/pay/method'
      preLoaderRoute: typeof PayMethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/processing': {
      id: '/pay/processing'
      path: '/pay/processing'
      fullPath: '/pay/processing'
      preLoaderRoute: typeof PayProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/verify': {
      id: '/pay/verify'
      path: '/pay/verify'
      fullPath: '/pay/verify'
      preLoaderRoute: typeof PayVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/': {
      id: '/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/$id': {
      id: '/payments/$id'
      path: '/payments/$id'
      fullPath: '/payments/$id'
      preLoaderRoute: typeof PaymentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$code/login': {
      id: '/company/$code/login'
      path: '/login'
      fullPath: '/company/$code/login'
      preLoaderRoute: typeof CompanyCodeLoginRouteImport
      parentRoute: typeof CompanyCodeRoute
    }
    '/company/$code/settings': {
      id: '/company/$code/settings'
      path: '/settings'
      fullPath: '/company/$code/settings'
      preLoaderRoute: typeof CompanyCodeSettingsRouteImport
      parentRoute: typeof CompanyCodeRoute
    }
    '/pay/receipt/$id': {
      id: '/pay/receipt/$id'
      path: '/pay/receipt/$id'
      fullPath: '/pay/receipt/$id'
      preLoaderRoute: typeof PayReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CompanyCodeRouteChildren {
  CompanyCodeLoginRoute: typeof CompanyCodeLoginRoute
  CompanyCodeSettingsRoute: typeof CompanyCodeSettingsRoute
}

const CompanyCodeRouteChildren: CompanyCodeRouteChildren = {
  CompanyCodeLoginRoute: CompanyCodeLoginRoute,
  CompanyCodeSettingsRoute: CompanyCodeSettingsRoute,
}

const CompanyCodeRouteWithChildren = CompanyCodeRoute._addFileChildren(
  CompanyCodeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutopayRoute: AutopayRoute,
  ContactRoute: ContactRoute,
  GatewayRoute: GatewayRoute,
  CompanyCodeRoute: CompanyCodeRouteWithChildren,
  PayCharityRoute: PayCharityRoute,
  PayMethodRoute: PayMethodRoute,
  PayProcessingRoute: PayProcessingRoute,
  PayVerifyRoute: PayVerifyRoute,
  PaymentsIdRoute: PaymentsIdRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
  PayReceiptIdRoute: PayReceiptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
